import { CHAPTERS } from "./chapters.mjs";
import { sha256 } from "./hash.mjs";
import { compareRuleIds, kernelText, sectionMarkdown, stripMarkers } from "./parse.mjs";
import { estimateTokens } from "./tokens.mjs";

export const MANAGED_BEGIN = "<!-- PRUMO:BEGIN";
export const MANAGED_END = "<!-- PRUMO:END -->";
export const README_BEGIN = "<!-- PRUMO:GENERATED:BEGIN -->";
export const README_END = "<!-- PRUMO:GENERATED:END -->";
export const KERNEL_TOKEN_BUDGET = 2500;
export const CHAPTER_PATH_HINT = "~/.prumo/protocol/chapters/<chapter>.md";

export function stamp(protocolVersion, sourceHash, extra = "") {
  const suffix = extra ? ` ${extra}` : "";
  return `<!-- Generated by Prumo. Protocol ${protocolVersion}. Source sha256:${sourceHash}. Do not edit: edit content/PRUMO.md and run npm run build.${suffix} -->`;
}

export function renderFullProtocol(ast, protocolVersion, sourceHash) {
  const body = stripMarkers(ast.lines.join("\n")).replace(/^<!--\s*prumo-protocol:[^\n]*-->\n/, "");
  return `${stamp(protocolVersion, sourceHash)}\n${body.trimEnd()}\n`;
}

export function identityParagraphs(ast) {
  const paragraphs = [];
  let buffer = [];
  for (const line of ast.intro) {
    if (/^(#|<!--|\*\*Contents\*\*|- Section|- Appendix|---)/.test(line)) {
      if (line.startsWith("**Contents**")) break;
      continue;
    }
    if (line.trim() === "") {
      if (buffer.length > 0) paragraphs.push(buffer.join(" "));
      buffer = [];
      continue;
    }
    buffer.push(line.trim());
  }
  if (buffer.length > 0) paragraphs.push(buffer.join(" "));
  return paragraphs.filter(paragraph => !/machine-readable markers/.test(paragraph));
}

export function routerTable(ast) {
  const bootstrap = ast.sections.find(section => section.number === 0);
  if (!bootstrap) return [];
  const lines = bootstrap.lines;
  const start = lines.findIndex(line => /^\| Situation \|/.test(line));
  if (start === -1) return [];
  const table = [];
  for (let index = start; index < lines.length && lines[index].startsWith("|"); index += 1) table.push(lines[index]);
  return table;
}

export function routerChapterIds(ast) {
  const ids = new Set();
  for (const row of routerTable(ast).slice(2)) {
    const cell = row.split("|")[2] ?? "";
    for (const match of cell.matchAll(/`([a-z-]+)`/g)) ids.add(match[1]);
  }
  return [...ids];
}

export function kernelRules(ast) {
  return ast.rules.filter(rule => rule.kernel).sort((a, b) => compareRuleIds(a.id, b.id));
}

export function reminderRules(ast) {
  return ast.rules.filter(rule => rule.reminder).sort((a, b) => compareRuleIds(a.id, b.id));
}

export function renderKernelBody(ast, protocolVersion) {
  const identity = identityParagraphs(ast);
  const rules = kernelRules(ast);
  const lines = [
    "# Prumo kernel",
    "",
    `Protocol ${protocolVersion}, ${ast.rules.length} rules (${ast.rules[0].id} to ${ast.rules.at(-1).id}). This kernel is always active. Chapters carry the rest and are loaded by the router below. Cite rules by id.`,
    "",
    ...identity,
    "",
    "## Always-on rules",
    ""
  ];
  for (const rule of rules) lines.push(`- **${rule.id}.** ${kernelText(rule)}`);
  lines.push("", "## Chapter router", "");
  lines.push(...routerTable(ast));
  lines.push(
    "",
    `Chapter files: \`${CHAPTER_PATH_HINT}\` (or under \`$PRUMO_HOME/protocol/chapters/\`). \`prumo chapter <id>\` prints one; \`prumo explain PRU-xx\` prints one rule with its chapter and related rules. The full protocol is at \`~/.prumo/protocol/full/PRUMO.md\` for audits and explicit full mode.`,
    "",
    "## State and delivery contract",
    "",
    "- Read `MapSource.md` first when it exists; keep it under the schema-2 headings and its hot-state budget; update it at the end of each block of work.",
    "- Every report states what was done, how it was verified (command and result, or \"not verified: reason\"), what was left out, known risks, and the honest grade of the delivery.",
    "- Never report a chapter as loaded without naming the trigger that fired. Never call a rule enforced when it is only prompted."
  );
  return `${lines.join("\n").trimEnd()}\n`;
}

export function renderKernel(ast, protocolVersion, sourceHash) {
  return `${stamp(protocolVersion, sourceHash)}\n${renderKernelBody(ast, protocolVersion)}`;
}

export function renderChapter(ast, chapter, protocolVersion, sourceHash) {
  const sections = chapter.sections.map(number => ast.sections.find(section => section.number === number)).filter(Boolean);
  const ruleIds = sections.flatMap(section => section.ruleIds);
  const lines = [
    stamp(protocolVersion, sourceHash, `Chapter: ${chapter.id}.`),
    `# Prumo chapter — ${chapter.title}`,
    "",
    `Chapter \`${chapter.id}\`. Rules ${ruleIds[0]} to ${ruleIds.at(-1)} (${ruleIds.length}). Loaded when: ${chapter.triggers.map(trigger => trigger.description).join("; ")}.${chapter.nonSuppressible ? " This chapter is never suppressed once triggered." : ""}`,
    ""
  ];
  for (const section of sections) lines.push(sectionMarkdown(section), "", "---", "");
  while (lines.at(-1) === "" || lines.at(-1) === "---") lines.pop();
  return `${lines.join("\n")}\n`;
}

export function managedBlock(body, protocolVersion) {
  const content = `${body.trimEnd()}\n`;
  const hash = sha256(content);
  return { text: `${MANAGED_BEGIN} protocol=${protocolVersion} hash=${hash} -->\n${content}${MANAGED_END}\n`, hash };
}

export function renderAgentBridge(ast, protocolVersion, sourceHash, variant) {
  const kernel = renderKernelBody(ast, protocolVersion);
  const block = managedBlock(kernel, protocolVersion);
  const header = `${stamp(protocolVersion, sourceHash, `Read by: ${variant.consumers}.`)}\n`;
  if (variant.frontMatter) return `${variant.frontMatter}\n${header}\n${block.text}`;
  return `${header}\n${block.text}`;
}

export const AGENT_VARIANTS = [
  { file: "CLAUDE.md", consumers: "Claude Code, project root and ~/.claude/CLAUDE.md" },
  { file: "AGENTS.md", consumers: "Codex CLI, Cursor, Grok Build and every agent that reads AGENTS.md" },
  { file: "GEMINI.md", consumers: "Gemini CLI" },
  { file: "grok-rule.md", consumers: "Grok Build global rule at ~/.grok/rules/prumo.md" },
  { file: "cursor-rule.mdc", consumers: "Cursor always-on rule at ~/.cursor/rules/prumo.mdc", frontMatter: "---\ndescription: Prumo operating protocol kernel\nalwaysApply: true\n---" }
];

export function renderReminder(ast, protocolVersion) {
  const rules = reminderRules(ast);
  const head = `PRUMO PROTOCOL ACTIVE. Protocol ${protocolVersion}, ${ast.rules.length} rules (${ast.rules[0].id} to ${ast.rules.at(-1).id}); every rule has a stable id and the kernel is normative.`;
  const body = rules.map(rule => `${kernelText(rule)} (${rule.id})`).join(" ");
  return `${head} ${body}`;
}

export function renderSkill(ast, protocolVersion, sourceHash) {
  const first = ast.rules[0].id;
  const last = ast.rules.at(-1).id;
  const dispatch = CHAPTERS.map(chapter => `- \`${chapter.id}\` → \`references/${chapter.id}.md\` — ${chapter.triggers.map(trigger => trigger.description).join("; ")}`).join("\n");
  return `---
name: prumo
description: >
  Prumo operating protocol for coding agents (protocol ${protocolVersion}, ${ast.rules.length} rules,
  ${first} to ${last}). Use for /prumo, "apply the protocol", "what does PRU-xx say",
  before a delivery report, when a test fails, when the work touches authentication,
  external input, secrets or personal data, and whenever the user asks for an opinion.
---

${stamp(protocolVersion, sourceHash, "Skill: claude.")}

# Prumo skill

The kernel below is always in force. Load a chapter from \`references/\` only when its
trigger is active, and say which trigger fired. Security is never skipped once a
PRU-210 trigger is touched.

## Dispatch

${dispatch}

## Kernel

${renderKernelBody(ast, protocolVersion).replace(/^# Prumo kernel\n\n/, "")}
## State protocol

- \`MapSource.md\` follows schema 2: see \`schemas/mapsource.md\`. Read it first, keep it under budget, update it at the end of each block of work.
- Suspicion items carry a closed severity: critical, high, medium, low.
- Root causes go to the ledger with id, symptom, cause, fix, regression test, file:line, commit.

## Output contract

Final report, in order: what was done; how it was verified (command and result, or "not verified: reason"); what was left out; known risks; the honest grade of the delivery (Bad, Weak, Acceptable, Good) with its weak point. Suggestions come last, marked as suggestions, with verdict and cost.
`;
}

export function renderMapSourceTemplate(protocolVersion) {
  return `---
prumo_protocol: ${protocolVersion}
schema: 2
updated_at: 1970-01-01T00:00:00Z
---

# Goal

One sentence, in the user's language.

# Active specification

## Scope

## Out of scope

## Acceptance criteria

## Assumptions

# Architecture map

File tree with one line per file; reference map in file:line form.

# Decisions

Decision, discarded alternatives, reason. Blockers and how they were worked around.

# Work fronts

- [ ] front — worktree, branch, scope, state, next step

# Suspicion zone

- SZ-0001 | severity: high | status: open | file: path/to/file.ext:42
  - condition:
  - impact:
  - evidence:
  - proposed fix:
  - introduced_at:
  - resolved_at:

# Root causes

- RC-0001 | symptom: | cause: | fix: | regression-test: | files: | commit:

# Project commands

# Glossary
`;
}

export function renderMapSourceSchemaDoc(protocolVersion) {
  return `${renderMapSourceTemplate(protocolVersion)}
---

Rules for this file: front matter with \`prumo_protocol\`, \`schema: 2\`, \`updated_at\`; the nine level-one headings above in this order; suspicion items as \`SZ-nnnn\` with a severity from critical, high, medium, low and a status from open, mitigated, resolved, wontfix; root causes as \`RC-nnnn\`. Hot-state budget: target 24 KB, warning 32 KB, compaction at 48 KB; closed items move to \`.prumo/history/\` with a one-line reference left behind.
`;
}

export function renderReadmeBlock(manifest) {
  const targets = manifest.targets.map(target => `\`${target}\``).join(", ");
  return `${README_BEGIN}
The protocol contains **${manifest.ruleCount} citable rules** (\`${manifest.ruleRange.first}\` to \`${manifest.ruleRange.last}\`) in ${manifest.sections.filter(section => section.number !== undefined).length} sections, compiled into a kernel of about ${manifest.kernel.tokens} tokens and ${manifest.chapters.length} chapters. Protocol version \`${manifest.protocolVersion}\`, source \`sha256:${manifest.sourceHash.slice(0, 12)}\`. Supported targets: ${targets}.
${README_END}`;
}

export function buildManifest(ast, { protocolVersion, sourceHash, kernelBody, reminder, targets }) {
  const rules = ast.rules.map(rule => {
    const chapter = CHAPTERS.find(entry => entry.sections.includes(rule.sectionNumber));
    return {
      id: rule.id,
      section: rule.sectionNumber,
      subsection: rule.subsection,
      title: rule.title ?? kernelText(rule).replace(/\.$/, "").slice(0, 80),
      tier: rule.kernel ? "kernel" : "chapter",
      reminder: rule.reminder,
      critical: rule.critical,
      chapter: chapter?.id,
      triggers: chapter ? chapter.triggers.map(trigger => trigger.id) : [],
      references: rule.references,
      enforcement: rule.enforcement,
      evalSuite: rule.evalSuite,
      source: { file: "content/PRUMO.md", line: rule.line }
    };
  });
  const kernelIds = rules.filter(rule => rule.tier === "kernel").map(rule => rule.id);
  return {
    generatedBy: "Prumo protocol compiler",
    protocolVersion,
    sourceHash,
    ruleCount: rules.length,
    ruleRange: { first: rules[0].id, last: rules.at(-1).id },
    sections: ast.sections.map(section => ({ number: section.number, appendix: section.appendix, title: section.title, line: section.line, rules: section.ruleIds })),
    chapters: CHAPTERS.map(chapter => ({
      id: chapter.id,
      title: chapter.title,
      sections: chapter.sections,
      defaultLoad: chapter.defaultLoad,
      nonSuppressible: Boolean(chapter.nonSuppressible),
      rules: rules.filter(rule => rule.chapter === chapter.id).map(rule => rule.id),
      tokens: estimateTokens(renderChapter(ast, chapter, protocolVersion, sourceHash)),
      triggers: chapter.triggers
    })),
    kernel: { rules: kernelIds, tokens: estimateTokens(kernelBody), budget: KERNEL_TOKEN_BUDGET },
    reminder: { rules: rules.filter(rule => rule.reminder).map(rule => rule.id), text: reminder, tokens: estimateTokens(reminder) },
    precedence: ["security and privacy", "data integrity", "the user's explicit decision", "an existing public contract", "the active specification", "the repository's convention", "Prumo's own preference"],
    critical: rules.filter(rule => rule.critical).map(rule => rule.id),
    coverage: summarizeCoverage(rules),
    targets,
    rules
  };
}

export function summarizeCoverage(rules) {
  const byCategory = {};
  for (const rule of rules) byCategory[rule.enforcement] = (byCategory[rule.enforcement] ?? 0) + 1;
  return byCategory;
}

export function renderCoverageReport(manifest) {
  const lines = [
    `# Protocol coverage — protocol ${manifest.protocolVersion}`,
    "",
    "Categories: ENFORCED (a mechanism prevents the violation), DETERMINISTICALLY_TESTED (a test in this repository checks it), BEHAVIOR_EVAL (an eval suite judges agent transcripts), DOCUMENTARY (descriptive text), MANUAL (prompted only; verified by human review). Prompted is not enforced (PRU-261).",
    "",
    "| Category | Rules |",
    "|---|---|"
  ];
  for (const [category, count] of Object.entries(manifest.coverage).sort()) lines.push(`| ${category} | ${count} |`);
  lines.push("", "| Rule | Category | Eval suite | Critical |", "|---|---|---|---|");
  for (const rule of manifest.rules) lines.push(`| ${rule.id} | ${rule.enforcement} | ${rule.evalSuite ?? ""} | ${rule.critical ? "yes" : ""} |`);
  return `${lines.join("\n")}\n`;
}
