import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { bridgeFileFor, sha256 } from "./paths.mjs";

export const BRIDGE_STATES = ["ABSENT", "ACTIVE", "PARTIAL", "FOREIGN", "DRIFTED", "BROKEN", "DISABLED"];

const BEGIN_PATTERN = /<!-- PRUMO:BEGIN protocol=([^\s]+) hash=([0-9a-f]{64}) -->\n?/;
const END_MARKER = "<!-- PRUMO:END -->";
const STAMP_PATTERN = /^<!-- Generated by Prumo\.[^\n]*-->\n?/m;

export function parseManagedBlock(text) {
  const source = String(text).replace(/\r\n?/g, "\n");
  const begin = source.match(BEGIN_PATTERN);
  if (!begin) return { present: false };
  const bodyStart = begin.index + begin[0].length;
  const endIndex = source.indexOf(END_MARKER, bodyStart);
  if (endIndex === -1) return { present: true, valid: false, reason: "missing PRUMO:END", version: begin[1], declaredHash: begin[2] };
  const body = source.slice(bodyStart, endIndex);
  const actualHash = sha256(body);
  return {
    present: true,
    valid: actualHash === begin[2],
    version: begin[1],
    declaredHash: begin[2],
    actualHash,
    body,
    start: begin.index,
    end: endIndex + END_MARKER.length
  };
}

export function classifyBridgeText(text, { currentVersion, currentHash, seedingEnabled = true } = {}) {
  const block = parseManagedBlock(text);
  if (!block.present) return { state: "FOREIGN", reason: "file exists without a Prumo managed block" };
  if (!block.valid) return { state: "DRIFTED", reason: block.reason ?? "managed block content does not match its hash", version: block.version };
  const outdated = (currentVersion && block.version !== currentVersion) || (currentHash && block.declaredHash !== currentHash);
  return {
    state: "ACTIVE",
    reason: outdated ? `managed block intact, protocol ${block.version} differs from installed ${currentVersion}` : "managed block intact",
    version: block.version,
    hash: block.declaredHash,
    outdated: Boolean(outdated),
    seedingEnabled
  };
}

export function detectBridge({ workspace, cli, currentVersion, currentHash, seedingEnabled = true }) {
  const file = bridgeFileFor(cli);
  const path = join(workspace, file);
  if (!existsSync(path)) {
    return { file, path, state: seedingEnabled ? "ABSENT" : "DISABLED", reason: seedingEnabled ? "no instruction file in the workspace" : "seeding disabled by PRUMO_SEED=0; no instruction file in the workspace" };
  }
  let text;
  try {
    if (!statSync(path).isFile()) return { file, path, state: "FOREIGN", reason: `${file} exists but is not a regular file` };
    text = readFileSync(path, "utf8");
  } catch (error) {
    return { file, path, state: "BROKEN", reason: `cannot read ${file}: ${error instanceof Error ? error.message : String(error)}` };
  }
  return { file, path, ...classifyBridgeText(text, { currentVersion, currentHash, seedingEnabled }) };
}

export function extractBlockFromArtifact(artifactText) {
  const block = parseManagedBlock(artifactText);
  if (!block.present || !block.valid) throw new Error("bridge artifact has no valid managed block");
  const source = String(artifactText).replace(/\r\n?/g, "\n");
  return { text: source.slice(block.start, block.end), version: block.version, hash: block.declaredHash };
}

export function appendManagedBlock(existingText, blockText) {
  const source = String(existingText).replace(/\r\n?/g, "\n");
  const separator = source.length === 0 ? "" : source.endsWith("\n\n") ? "" : source.endsWith("\n") ? "\n" : "\n\n";
  return `${source}${separator}${blockText.trimEnd()}\n`;
}

export function removeManagedBlock(text) {
  const source = String(text).replace(/\r\n?/g, "\n");
  const block = parseManagedBlock(source);
  if (!block.present || block.start === undefined) return { text: source, removed: false, empty: false };
  let remaining = `${source.slice(0, block.start)}${source.slice(block.end)}`;
  remaining = remaining.replace(STAMP_PATTERN, "");
  const empty = remaining.trim().length === 0;
  return { text: empty ? "" : remaining.replace(/\n{3,}/g, "\n\n").replace(/^\n+/, "").replace(/\n+$/, "\n"), removed: true, empty };
}

export function replaceManagedBlock(text, blockText) {
  const removed = removeManagedBlock(text);
  return appendManagedBlock(removed.text, blockText);
}
